version: '3'

volumes:
  mysql:
  code:

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
    ports:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
  webserver:
    build: .
    volumes:
      - code:/app
    ports:
      - 80
      - 443
    depends_on:
      - database
    links:
      - database
  composer:
    image: composer
  drush:
    image: drush/drush
    volumes:
      - code:/app 
  git:
    image: alpine/git 
    volumes:
      - $HOME:/root
      - .:/git

